source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'PodTestFrame2_Example', :exclusive => true do
  pod 'PodTestFrame2', :path => '../'
end

target 'PodTestFrame2_Tests', :exclusive => true do
  pod 'PodTestFrame2', :path => '../'

  
end
